### ISSUE TITLE
Hisat2Workflowでthreadオプションが効かない

### ISSUE THREAD

**Issue by nasunom** [pitagora-network/pitagora-cwl#1]
hisat2-se.cwlで定義されている process オプションが Hisat2Workflow-se.cwl に含まれていないため、workflowのhisat2ステップが現状シングルスレッドでしか動作しない。

**Comment by yyabuki** [comment]
added a thread option in each Hisat2 workflow.

**Comment by inutano** [comment]
*the issue was already resolved*
