### ISSUE TITLE
kallisto workflow fails

### ISSUE THREAD

**Issue by inutano** [pitagora-network/pitagora-cwl#16]
with an instance of memory 2GB (t3.small)

**Comment by bonohu** [comment]
Error report.
I can make use of it in two months ago with B.mori transcripts.
But, now with gencode human (v30) transcripts with command line below,

`cwltool ~/Downloads/pitagora-cwl/tools/kallisto/index/kallisto_index.cwl \
--fasta_files gencode.v30.transcripts.fa.gz \
--index_name Human
`
I cannot make it. Error on the screen is below.

`ERROR [job kallisto_index.cwl] Job error:
Error collecting output for parameter 'index_file':
pitagora-cwl/tools/kallisto/index/kallisto_index.cwl:46:7: Did not find output file with glob pattern: '['Human']'
WARNING [job kallisto_index.cwl] completed permanentFail
{}
WARNING Final process status is permanentFail`

**Comment by bonohu** [comment]
I tried with the reference change from gencode to Ensembl human.

`cwltool ~/Downloads/pitagora-cwl/tools/kallisto/index/kallisto_index.cwl \
--fasta_files Homo_sapiens.GRCh38.cdna.all.fa.gz \
--index_name Human` 

with success....

Do you have any thoughts about it?

**Comment by inutano** [comment]
Can you run it with the options `—debug` and `—leave-tmpdir` and check what happened? leave-tmpdir option will remain the files created during the run so you can check inside.

**Comment by bonohu** [comment]
It seems that the error was caused by insufficient memory.
I could successfully finish constructing kallisto index in Mac mini (memory 64GB, 32GB for docker) while I failed in macbook pro(memory 16GB, 8GB for docker).
Thanks for your kind and prompt advice.

**Comment by inutano** [comment]
closing this since it's already solved
