### ISSUE TITLE
download-sra cannot find `ERR2862454`

### ISSUE THREAD

**Issue by s-tahara** [pitagora-network/pitagora-cwl#36]
I wanna get fastq file as follows:

```
cwltool --singularity --debug "https://raw.githubusercontent.com/pitagora-network/pitagora-cwl/master/workflows/download-fastq/download-fastq.cwl" "ERX2868692_job.yml"
```

ERX2868692_job.yml :
```
run_ids:
- ERR2862454
nthreads: 4
```

but returned error
```
DEBUG [job download_sra] initial work dir {}
INFO [job download_sra] /tmp/12219045.30.intel.q/kdmz8lop$ singularity \
    --quiet \
    exec \
    --contain \
    --ipc \
    --pid \
    --home \
    /tmp/12219045.30.intel.q/kdmz8lop:/NdnVgK \
    --bind \
    /tmp/12219045.30.intel.q/p77m4xhe:/tmp:rw \
    --pwd \
    /NdnVgK \
    /lustre7/home/s-tahara/DROMPA/code_debug/quay.io_inutano_download-sra:0.2.1.sif \
    download-sra \
    -r \
    ebi \
    ERR2862454
--2021-03-18 03:02:40--  ftp://ftp.sra.ebi.ac.uk/vol1/err/ERR286/004/ERR2862454
           => 'ERR2862454.sra'
Resolving ftp.sra.ebi.ac.uk... 193.62.197.74
Connecting to ftp.sra.ebi.ac.uk|193.62.197.74|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /vol1/err/ERR286/004 ... done.
==> SIZE ERR2862454 ... done.

==> PASV ... done.    ==> RETR ERR2862454 ... 
No such file 'ERR2862454'.

WARNING [job download_sra] completed permanentFail
```

Environment is NIG supercomputer

How can I do ?

**Comment by inutano** [comment]
Hi @s-tahara , it seems the EBI does not host the data in their FTP site for some reason, nor NCBI does. It is available on DDBJ's FTP site, so you could use the repository option as follows:

```
run_ids:
  - ERR2862454
nthreads: 4
repo: ddbj
```

I've found a bug in the `download-sra` container and fixed it in the latest commit, so please make sure to update the CWL definition file `https://github.com/pitagora-network/pitagora-cwl/blob/master/tools/download-sra/download-sra.cwl`. If you've cloned this repository, then you just can use the `git pull` command to update the whole repository.

Note that the NIG supercomputer provides their data from `/usr/local/resources`, and you can find the full list of data they archive in `/usr/local/resources/dra/meta/list/sralist`. You can copy the data to your home directory and run `https://github.com/pitagora-network/pitagora-cwl/blob/master/tools/pfastq-dump/pfastq-dump.cwl` with it to decompress to fastq.

Let me know if I can help you any further!

**Comment by s-tahara** [comment]
@inutano Thank you so much for your kind reply!

I could fix `WARNING [job download_sra] completed permanentFail` error, and I'm using new version of CWL difinition file.

but I encountered another error (fastq-dump) : #38

I built another issue, so could you help me there?

Thank you so much for your kindness.
