### ISSUE TITLE
samtools view cwl? 

### ISSUE THREAD

**Issue by vortexing** [pitagora-network/pitagora-cwl#8]
I'm a complete CWL novice but am involved in a project testing workflows at my institution.  I am interested in trying to run this workflow you've made:
https://github.com/pitagora-galaxy/cwl/blob/master/workflows/bwa/BwaWorkflow-pe.cwl

But don't see the samtools-view.cwl file that is referred to in this workflow in your repo.  Am I just missing it or missing something else?  

Edited to add:  I also can't see samtools-version.cwl.

**Comment by inutano** [comment]
Hi @vortexing , thanks for trying to use our CWL workflows. I am very sorry for my late reply.

We've been working to update the definitions of tools and workflows, and some are not yet done. I found that the bwa workflow uses the old samtools tool definition file, and it will take a time to update the whole steps of the workflow, so I made a branch of the workflows https://github.com/pitagora-galaxy/cwl/tree/old-workflows where the first implementations are. There is the `samtools-view.cwl` file and others for the bwa workflow. 

Let me know if you still have any question.
